# Generated by Django 6.0.4 on 2026-04-08 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('technology', 'Technology'), ('health', 'Health'), ('economics', 'Economics'), ('lifestyle', 'Lifestyle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='blog',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
